baseURL = "https://Z41F3R.github.io/"
title = "Z41F3R"
theme = "hugo-coder" 
languageCode = "en" 
defaultContentLanguage = "en" 
enableEmoji = true

[pagination]
  pagerSize = 6

[services]
  [services.disqus]
  # shortname = "yourdiscussshortname"

[markup.highlight]
  noClasses = false

[params]
author = "Z41F3R"
description = "HACKING ETICAL"
keywords = "blog,developer,personal"
info = ["Ethical Hacking", "Red Teamer", "Offensive Security"]
avatarURL = "images/avatar.png"
faviconSVG = "/images/avatar.svg"
dateFormat = "January 2, 2006"
since = 2019
commit = "https://github.com/luizdepra/hugo-coder/tree/"
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []
customJS = []
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/Z41F3R"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "z41f3r"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Post/WriteUps"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

#[[languages.en.menu.main]]
#name = "Contact"
#weight = 4
#url = "contact/"

[languages.es]
languageName = ":chile:"
title = "Z4IF3R"

[languages.es.params]
author = "Z41F3R"
info = ["Hacking Ético", "Red Teamer", "Seguridad Ofensiva"]
description = ""
keywords = ""

[[languages.es.menu.main]]
name = "z41f3r"
weight = 1
url = "about/"

[[languages.es.menu.main]]
name = "Blogs/WriteUps"
weight = 2
url = "posts/"

[[languages.es.menu.main]]
name = "Proyectos"
weight = 3
url = "proyectos/"

#[[languages.es.menu.main]]
#name = "Contacto"
#weight = 4
#url = "contact/"
